name = "lean_v3_1"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanV31"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "LeanV31"

[[lean_lib]]
name = "LeanV32"
